name: Build APK

on:
  push:
    branches:
      - main  # Trigger build on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger build on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          sudo apt-get install -y python3-dev python3-setuptools python3-pip \
                                 build-essential libssl-dev libffi-dev \
                                 libsqlite3-dev libjpeg-dev libfreetype6-dev \
                                 liblcms2-dev libopenjp2-7-dev libpng-dev \
                                 libmysqlclient-dev libssl-dev

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk-linux
          cd $HOME/android-sdk-linux
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          yes | $HOME/android-sdk-linux/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk-linux/cmdline-tools/bin/sdkmanager --update
          $HOME/android-sdk-linux/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
          
